demoazure1/Models/ErrorViewModel.cs
namespace demoazure1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

demoazure1/Models/LeadEntity.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace demoazure1.Models
{
    public class LeadEntity
    {
        [Key]
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Date")]
        [Required]
        
        public DateTime LeadDate { get; set; }

        [DisplayName("Lead Source")]
        [Required]
        [StringLength(50)]
        public string LeadSource { get; set; }
        [Required]
        [StringLength(10)]
        public string Name { get; set; }
       
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
        ErrorMessage = "Entered phone format is not valid.")]
        public string mobile { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

    }
}

demoazure1/Controllers/HomeController.cs
using demoazure1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demoazure1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

demoazure1/Controllers/LeadEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using demoazure1.Data;
using demoazure1.Models;

namespace demoazure1.Controllers
{
    public class LeadEntitiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeadEntitiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LeadEntities
        public async Task<IActionResult> Index()
        {
              return _context.Leads != null ? 
                          View(await _context.Leads.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Leads'  is null.");
        }

        // GET: LeadEntities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Leads == null)
            {
                return NotFound();
            }

            var leadEntity = await _context.Leads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leadEntity == null)
            {
                return NotFound();
            }

            return View(leadEntity);
        }

        // GET: LeadEntities/Create
        
        public IActionResult Create()
        {
            return View();
        }

        // POST: LeadEntities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("Id,LeadDate,LeadSource,Name,mobile,Email")] LeadEntity leadEntity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(leadEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(leadEntity);
        }

        // GET: LeadEntities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Leads == null)
            {
                return NotFound();
            }

            var leadEntity = await _context.Leads.FindAsync(id);
            if (leadEntity == null)
            {
                return NotFound();
            }
            return View(leadEntity);
        }

        // POST: LeadEntities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LeadDate,LeadSource,Name,mobile,Email")] LeadEntity leadEntity)
        {
            if (id != leadEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leadEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeadEntityExists(leadEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leadEntity);
        }

        // GET: LeadEntities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Leads == null)
            {
                return NotFound();
            }

            var leadEntity = await _context.Leads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leadEntity == null)
            {
                return NotFound();
            }

            return View(leadEntity);
        }

        // POST: LeadEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Leads == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Leads'  is null.");
            }
            var leadEntity = await _context.Leads.FindAsync(id);
            if (leadEntity != null)
            {
                _context.Leads.Remove(leadEntity);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeadEntityExists(int id)
        {
          return (_context.Leads?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

demoazure1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

demoazure1/Views/LeadEntities/Create.cshtml
@model demoazure1.Models.LeadEntity

@{
    ViewData["Title"] = "Create";
}
<head>
    <script>
        function Createmethod() {
            var dateFormat =
                document.forms.RegForm.Date.value;
            var name =
                document.forms.RegForm.leadsource.value;
            var name =
                document.forms.RegForm.Name.value;
            var email =
                document.forms.RegForm.EMail.value;
            var phone =
                document.forms.RegForm.Mobile.value;
           
          
              //Javascript reGex for Email Validation.
            var regPhone=/^\d{10}$/;                                 
            var regName = /\d+$/g;   
            
            var dateFormat = /(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-\d{4}/;

            if (!startDate.match(dateFormat)) {
                window.alert("'Start Date' must be in format: DD-MM-YYYY");
                dateFormat.focus();
                return false;
            }

            if (name == "" || regName.test(name)) {
                window.alert("Please enter your name properly.");
                name.focus();
                return false;
            }
 
            //if (email == "" || !regEmail.test(email)) {
            //    window.alert("Please enter a valid e-mail address.");
            //    email.focus();
            //    return false;
            //}
        
           
            if (phone == "" || !regPhone.test(phone)) {
                alert("Please enter valid phone number.");
                phone.focus();
                return false;
            }
        
          
        
            return true;
        }
    </script>
    </head>
<h1>Create</h1>

<h4>LeadEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" name="RegForm" onsubmit="return Createmethod()" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeadDate" class="control-label"></label>
                <input asp-for="LeadDate" class="form-control" name="Date" />
                <span asp-validation-for="LeadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeadSource" class="control-label"></label>
                <input asp-for="LeadSource" class="form-control" name="leadsource" type="text" pattern="[A-Za-z] {15}" />
                <span asp-validation-for="LeadSource" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" type="text"  pattern="[A-Za-z] {15} " name="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mobile" class="control-label"></label>

                <input  asp-for="mobile"  class="form-control" name="Mobile"/>
                <span asp-validation-for="mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email"  class="form-control"  name="EMail" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create"  class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

demoazure1/Views/LeadEntities/Delete.cshtml
@model demoazure1.Models.LeadEntity

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeadEntity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeadDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeadDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeadSource)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeadSource)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

demoazure1/Views/LeadEntities/Details.cshtml
@model demoazure1.Models.LeadEntity

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LeadEntity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeadDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeadDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeadSource)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeadSource)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

demoazure1/Views/LeadEntities/Edit.cshtml
@model demoazure1.Models.LeadEntity

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LeadEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="LeadDate" class="control-label"></label>
                <input asp-for="LeadDate" class="form-control" />
                <span asp-validation-for="LeadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeadSource" class="control-label"></label>
                <input asp-for="LeadSource" class="form-control" />
                <span asp-validation-for="LeadSource" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mobile" class="control-label"></label>
                <input asp-for="mobile" class="form-control" />
                <span asp-validation-for="mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

demoazure1/Views/LeadEntities/Index.cshtml
@model IEnumerable<demoazure1.Models.LeadEntity>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LeadDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeadSource)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LeadDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeadSource)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

demoazure1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demoazure1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/demoazure1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">demoazure1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeadEntities" asp-action="Index">CRM Leads</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - demoazure1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>